---
  - name: Vault Tools | Dependencies
    apt: pkg="{{item}}" state="present"
    with_items:
      - git
    when: vault_present | failed
    tags:
      - vault

  - name: Vault Tools | Install https://github.com/Voronenko/hashi_vault_utils
    git: repo=https://github.com/Voronenko/hashi_vault_utils.git dest="{{vault_console_tools_path}}" update=no bare=yes accept_hostkey=yes
    when: vault_present | failed
    tags:
      - vault
